### PR TITLE
removed "-g users" option from useradd

### PR DESCRIPTION
**Pull request by herobrauni**
users will be members of their own group

## Description

Removes the "-g users" option from useradd in the usercreation, each user now gets its own group.

## Affected issues

See #628

## Pull request checklist

* [x] I have tested my code
* [x] I have read the [contributing guide](https://github.com/AnarchyLinux/installer/blob/HEAD/CONTRIBUTING.md)
* [x] I have followed best practices and commented my code well

### CODE REVIEW

**Comment by erazemkokot** [comment]
Have you checked that none of the scripts depend on the "users" group?

**Comment by herobrauni** [comment]
> Have you checked that none of the scripts depend on the "users" group?

The only lines I could find are in "extra\shellrc\.zshrc".
They dont use the same "users" and suggestions still work fine.

We could add the new accounts to "users" by `useradd -G users`, but I can't see any reason to.

**Comment by erazemkokot** [comment]
Ok, cool, I'll merge it once I recheck it today ;)

**Comment by trwnh** [comment]
Per https://wiki.archlinux.org/index.php/users_and_groups
>users:
>The primary group for users when user private groups are not used (generally not recommended), e.g. when creating users with `USERGROUPS_ENAB no` in `/etc/login.defs` or the `-N/--no-user-group` option of *useradd*. 

There's certainly no *harm* in adding users to the `users` group, but there's no benefit either.

**Comment by erazemkokot** [comment]
@trwnh If we add a user to the `users` group, then `useradd` won't make a group with that user's name. Also this practice of having all the users in the same group is not recommended since all the users will be able to access each other's files if I understand it correctly.

**Pull request merged**
