### PR TITLE
Variable correction

### PR DESCRIPTION
**Pull request by Segdon**
## Pull request checklist

* [ ] I have tested my code
* [ ] I have read the [contributing guide](https://github.com/AnarchyLinux/installer/blob/HEAD/CONTRIBUTING.md)
* [ ] I have followed best practices and commented my code well

### CODE REVIEW

**Comment by FredBezies** [comment]
About French translation: why am I deleted from file history?

I'm disappointed to notice I'm not added in maintainer list.

Well, if it is going this way...

**Comment by Segdon** [comment]
> About French translation: why am I deleted from file history?
> 
> I'm disappointed to notice I'm not added in maintainer list.
> 
> Well, if it is going this way...

Sorry @FredBezies ,

I'm quite new at this and merely looking for a way to help a project that I like. I was told to put my name in the contribution so that there was a contact point in case of problems.

I'm happy to put anything and everybody in it who wants to be mentioned. More over the translation-effort is far from finished, so I hope that by my mistake I didn't discourage you from contributing more.

**Comment by FredBezies** [comment]
@Segdon : just add me back -> FredBezies - fredbezies at gmail dot com.

You should previous contributors like libcg (Clément Guérin), masshat (Massine Bitam) and Bricabraque

That's all.

**Comment by erazemkokot** [comment]
@FredBezies sorry for the mishap. I'd also like to ask you to check and compare the french translation file from the pacman-fix branch with the one from master.

Currently 'pacman-fix' is the development branch and most of the changes to Anarchy happen there, and you'd be doing us a big favour by updating that file instead of the one on master, so we don't have to merge all the changes.

**Comment by erazemkokot** [comment]
@Segdon, you should add yourself as a maintainer only on the languages you'll help translate to, not the ones you restructure, sorry for not being clear enough about this.

If you do wanna translate for French, you can easily add both of you as maintainers, but don't remove all other previous maintainers, add them like in the english.conf file:

```
# Original Maintainer: Deadhead (Dylan Schacht)
```

**Comment by FredBezies** [comment]
@erazemkokot looked at the file and it seems to be OK. Only added back contributors and added myself as maintainer too. See: https://github.com/AnarchyLinux/installer/pull/953

**Pull request merged**
