### PR TITLE
mkdir short syntax

### PR DESCRIPTION
**Pull request by yousefvand**
## Description

Short syntax for `mkdir -p`

### CODE REVIEW

**Comment by erazemkokot** [comment]
Hi,

Thanks for the pull request, but brace expansion is a "bashism".

We're trying to make Anarchy's code as POSIX-compliant as possible, which means that bash-specific features should not be added if they can be avoided. Although we're currently not nearly fully POSIX compliant, we still prefer not adding non-POSIX compliant code.

**Comment by yousefvand** [comment]
Hi
Thanks, I appreciate the clarification.
I was trying to find a use-case when theses scripts should be run in an environment without bash but couldn't figure out (I'm new to Arch Linux), any idea?

**Comment by erazemkokot** [comment]
Although I agree there aren't many, we might want to use the installer on distros similar to Arch, which might not have bash preinstalled. I also think it's better to be POSIX compliant in general, but this is my opinion, not our whole team's.

And of course there are still some pieces of code, where avoiding bash would make things more complicated (like arrays).

So while there aren't many use cases, I still think being as (future- and backwards-) compatible as possible would be better for the project, but I'm open to being convinced otherwise.

**Comment by yousefvand** [comment]
Very informative. Thanks.

**Pull request closed without merging**
